name: 🚀 Deploy Website to Hostinger FTP

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: 🎉 Đẩy code lên Hostinger
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: 📂 Sync Frontend (Giao Diện)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        local-dir: ./public_html/
        server-dir: ./
        log-level: verbose
        exclude: |
          **/.git*/**

    - name: 📂 Sync Backend (Máy Chủ)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        local-dir: ./backend/
        server-dir: ../backend/
        log-level: verbose
        exclude: |
          **/.git*/**
          **/.env
          **/data/**
          **/uploads/**
          **/node_modules/**
